# your domain
domain: "34.96.200.15"

# database url
database_url: "postgres://postgres:123456@127.0.0.1:5432/proxy5"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  #- https://example.com/source.yaml
