#模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://hoochanlon.github.io/w3-goto-world/%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91%E3%80%81%E6%9A%97%E7%BD%91%E3%80%81%E9%9B%B6%E7%BD%91/%E5%85%8D%E8%B4%B9ss%E3%80%81ssr%E3%80%81vmess%E5%88%86%E4%BA%AB/

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray20201027
- type: subscribe
  options:
    url: https://iwxf.netlify.app
- type: subscribe
  options:
    url: https://subhaha.xyz/link/9sRfg4gLBAcZwud7?sub=3&extend=1
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/gotodown/scientice/master/sub/subscrib-1021.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cogutt/PaidNode/master/v2raysub
- type: subscribe
  options:
    url: https://starlink.cx/api/v1/client/subscribe?token=4b6d37e4a5a7bb9c263be2c0a31b151c
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cogutt/freeV2ray/master/v2rayShare20201101
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/gotodown/scientice/master/sub/subscrib.txt
- type: subscribe
  options:
    url: https://gooii.ml/v2ray/sub/vmess.html
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
- type: subscribe
  options:
    url: https://jiang.netlify.com
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
## from github
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cogutt/PaidNode/master/v2raysub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cogutt/fastNode/master/getNode
- type: subscribe
  options:
    url: https://papaya-rss.com/link/BsMwjuvmQBWjFWAP?sub=3
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

#tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

- type: tgchannel
  options:
    channel: Xinana_awsl
    num: 1000
- type: tgchannel
  options:
    channel: daolis_miao
    num: 1000
- type: tgchannel
  options:
    channel: TG_Mtproxy_1
    num: 1000
- type: tgchannel
  options:
    channel: V2List
    num: 1000
- type: tgchannel
  options:
    channel: sharecentre
    num: 1000
- type: tgchannel
  options:
    channel: vmesssr
    num: 1000
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
# 某个网站抓取
- type: web-freessrxyz
  options:
